'use strict';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const message=$('#message'), listen=$('#listen');
let busy=false;
function count(){ $('#count').textContent=`${message.value.length}/400`; }
message.addEventListener('input',count);count();
const selected=()=>$$('.zone-options input:checked').map(i=>i.value);
function syncZones(){if(busy)return;const ids=selected();$$('.map-node').forEach(n=>{const active=ids.includes(n.dataset.node);n.setAttribute('class',`map-node${active?' selected':''}`);$('.node-state',n).textContent=active?'Pronto':'Non selezionata';});$$('[data-path]').forEach(p=>p.setAttribute('class',ids.includes(p.dataset.path)?'selected':''));$('#delivery-count').textContent='0';$('#progress').style.width='0';$('#map-status').textContent='Simulazione pronta';$('#demo-feedback').textContent=ids.length?`${ids.length} postazioni selezionate. Pronto per la prova.`:'Seleziona almeno una postazione.';}
$$('.zone-options input').forEach(i=>i.addEventListener('change',syncZones));syncZones();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function broadcast(){if(busy)return {status:'busy'};const ids=selected();if(!message.value.trim()){$('#demo-feedback').textContent='Scrivi il messaggio prima di avviare la prova.';message.focus();return {error:'empty_message'};}if(!ids.length){$('#demo-feedback').textContent='Seleziona almeno una postazione.';return {error:'no_zones'};}busy=true;document.dispatchEvent(new CustomEvent('otc:broadcast',{detail:'start'}));$('#broadcast').disabled=true;$$('.zone-options input').forEach(i=>i.disabled=true);message.readOnly=true;$('#broadcast').textContent='Diffusione in corso…';$('#delivery-count').textContent='0';$('#map-status').textContent='Preparazione del messaggio';$('#demo-feedback').textContent='Simulazione: preparazione del messaggio vocale…';$('#progress').style.width='15%';ids.forEach(id=>{$(`[data-node="${id}"]`).classList.remove('done');$(`[data-path="${id}"]`).setAttribute('class','sending');$('.node-state',$(`[data-node="${id}"]`)).textContent='In attesa';});await sleep(900);$('#map-status').textContent='Trasferimento alle postazioni';$('#progress').style.width='40%';ids.forEach(id=>{$(`[data-node="${id}"]`).classList.add('sending');$('.node-state',$(`[data-node="${id}"]`)).textContent='Ricezione';});await sleep(1000);$('#map-status').textContent='Riproduzione simulata';$('#demo-feedback').textContent='Simulazione: le postazioni selezionate riproducono il messaggio.';ids.forEach(id=>$('.node-state',$(`[data-node="${id}"]`)).textContent='Riproduzione');$('#progress').style.width='70%';await sleep(1200);ids.forEach(id=>{const n=$(`[data-node="${id}"]`);n.classList.remove('sending');n.classList.add('done');$('.node-state',n).textContent='Completato';$(`[data-path="${id}"]`).setAttribute('class','done');});$('#delivery-count').textContent=String(ids.length);$('#progress').style.width='100%';$('#map-status').textContent='Prova completata';$('#demo-feedback').textContent=`Prova completata su ${ids.length} postazioni. Nessun messaggio è stato inviato a impianti reali.`;$('#broadcast').innerHTML='Ripeti la prova <span>↗</span>';$('#broadcast').disabled=false;$$('.zone-options input').forEach(i=>i.disabled=false);message.readOnly=true;busy=false;document.dispatchEvent(new CustomEvent('otc:broadcast',{detail:'complete'}));return {status:'simulated',stations:ids.length};}
$('#broadcast').addEventListener('click',broadcast);
const features={audio:{number:'01 / AUDIO E PAROLA',title:'Le parole meritano<br>di essere ascoltate.',description:'Dalla prima all’ultima fila, il punto di partenza è capire come si comporta il suono nel tuo ambiente. Poi scegliere e posizionare l’impianto giusto.',list:['Studio delle esigenze di ascolto','Microfoni e diffusori integrati','Comandi semplici per l’uso quotidiano']},luce:{number:'02 / LUCE E ATMOSFERA',title:'La luce giusta.<br>Al momento giusto.',description:'Celebrazioni, incontri e visite hanno esigenze diverse. Un progetto di illuminazione può valorizzare gli spazi e rendere più semplice la gestione degli scenari.',list:['Illuminazione degli spazi e dei percorsi','Scenari da definire con la comunità','Integrazione con gli impianti compatibili']},controllo:{number:'03 / AUTOMAZIONE E CONTROLLO',title:'Più semplice.<br>Ogni giorno.',description:'Audio, luci e programmazioni: l’obiettivo è ridurre le operazioni quotidiane e offrire comandi comprensibili alle persone che usano davvero gli ambienti.',list:['Funzioni su misura per l’impianto','Programmazioni e comandi centralizzati','Formazione e assistenza all’utilizzo']}};
$$('[data-feature]').forEach(b=>b.addEventListener('click',()=>{const f=features[b.dataset.feature];document.dispatchEvent(new CustomEvent('otc:feature',{detail:b.dataset.feature}));$$('[data-feature]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#feature-number').textContent=f.number;$('#feature-title').innerHTML=f.title;$('#feature-description').textContent=f.description;$('#feature-list').replaceChildren(...f.list.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('#explorer-scene').classList.toggle('light',b.dataset.feature==='luce');}));
function openDialog(d){d.showModal();document.body.classList.add('no-scroll');}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>document.body.classList.remove('no-scroll'));$('[data-close]',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});});
let step=0, answers={sector:'pubblico',need:'bandi',scope:'nuovo'};
const sectors=[['pubblico','Comune o ente pubblico','Territorio, cittadini e spazi pubblici'],['religioso','Parrocchia o ente religioso','Ascolto, liturgia e vita della comunità']];
const needs={pubblico:[['bandi','Comunicare con i cittadini','Bando pubblico — Menestrello 2026'],['sala','Migliorare la sala consiliare','Audio, video e gestione degli interventi'],['impianti','Integrare gli impianti','Luce, automazione e gestione degli ambienti']],religioso:[['audio','Far capire meglio le parole','Amplificazione e intelligibilità'],['campane','Gestire campane e orari','Automazione e riproduzione sonora'],['impianti','Semplificare la gestione','Luce, automazione e ambienti'] ]};
const scopes=[['nuovo','Partire da un nuovo impianto','Progettare la soluzione sulle esigenze del luogo'],['esistente','Valorizzare quello che c’è','Verificare compatibilità e possibilità di integrazione']];
function renderWizard(){const names=['sector','need','scope'],labels=['In quale contesto lavoriamo?','Qual è il risultato più importante?','Da quale situazione partiamo?'],titles=['Partiamo dal tuo mondo.','Cosa vuoi migliorare?','Il tuo punto di partenza.'];$('#config-title').textContent=titles[step];$('#wizard-counter').textContent=`${step+1} DI 3`;const options=step===0?sectors:step===1?needs[answers.sector]:scopes;$('#wizard-body').innerHTML=`<fieldset><legend>${labels[step]}</legend>${options.map(([v,t,d])=>`<label class="choice"><input required type="radio" name="${names[step]}" value="${v}" ${answers[names[step]]===v?'checked':''}><span><strong>${t}</strong><small>${d}</small></span></label>`).join('')}</fieldset>`;$('#wizard-back').disabled=step===0;$('#wizard-next').textContent=step===2?'Scopri la soluzione ↗':'Continua ↗';}
function startConfig(sector){step=0;answers={sector:sector==='religioso'?'religioso':'pubblico',need:sector==='religioso'?'audio':'bandi',scope:'nuovo'};$('#config-form').hidden=false;$('#project-result').hidden=true;renderWizard();openDialog($('#config-dialog'));}
$$('[data-config]').forEach(b=>b.addEventListener('click',()=>startConfig(b.dataset.config)));
$('#wizard-back').addEventListener('click',()=>{step=Math.max(0,step-1);renderWizard();});
$('#config-form').addEventListener('submit',e=>{e.preventDefault();const name=['sector','need','scope'][step];const val=new FormData(e.currentTarget).get(name);if(!val)return;if(name==='sector'&&answers.sector!==val)answers.need=needs[val][0][0];answers[name]=val;if(step<2){step++;renderWizard();$('#config-title').setAttribute('tabindex','-1');$('#config-title').focus();}else showResult();});
const packages={bandi:{title:'Bando pubblico — Menestrello 2026',intro:'Una prima traccia per dare voce al territorio, da una singola postazione a più zone.',items:['Messaggi da testo, registrazione o file audio','Diffusione per postazioni e zone, con programmazione','Valutazione dei ricevitori esistenti e della connettività']},sala:{title:'Una sala dove partecipare',intro:'Audio, immagini e gestione degli interventi al servizio del confronto.',items:['Analisi dei posti e degli usi della sala','Microfoni e diffusione sonora','Valutazione di streaming, videoproiezione e votazione']},audio:{title:'La parola, al centro',intro:'Un percorso per rendere l’ascolto più chiaro negli spazi della comunità.',items:['Sopralluogo e valutazione dell’ambiente acustico','Scelta e posizionamento di microfoni e diffusori','Comandi semplici, collaudo e formazione']},campane:{title:'Il suono della tua comunità',intro:'Una soluzione da definire fra automazione degli impianti campanari e riproduzione elettronica.',items:['Valutazione dell’impianto e delle esigenze','Programmazioni di orari e ricorrenze','Definizione di comandi, volumi e assistenza']},impianti:{title:'Ambienti che lavorano insieme',intro:'Una prima analisi delle possibilità di integrazione degli impianti.',items:['Rilievo degli impianti e delle funzioni desiderate','Studio di luce, scenari e automazione','Definizione delle compatibilità e dei comandi']}};
let resultText='';
function showResult(){const p=packages[answers.need];$('#config-form').hidden=true;$('#project-result').hidden=false;$('#config-title').textContent='Il tuo progetto comincia qui.';$('#wizard-counter').textContent='LA TUA PRIMA TRACCIA';resultText=`OTC — Prima traccia del progetto\n\nContesto: ${sectors.find(x=>x[0]===answers.sector)[1]}\nEsigenza: ${p.title}\nSituazione: ${scopes.find(x=>x[0]===answers.scope)[1]}\n\n${p.intro}\n${p.items.map(x=>'• '+x).join('\n')}\n\nIndicazione orientativa generata dalle scelte nel configuratore. Non è un preventivo né un progetto tecnico. Compatibilità e prestazioni da validare con sopralluogo.\n\nContatti: info@otconline.it — 070 8607703`;
$('#project-result').innerHTML=`<div class="result-summary"><h3>${p.title}</h3><p>${p.intro}</p><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul></div><p class="result-note">${answers.scope==='esistente'?'Partiremo dall’impianto esistente, verificando cosa può essere mantenuto e integrato.':'Il sopralluogo aiuterà a definire dimensioni, posizionamento e requisiti della nuova installazione.'}</p><p class="result-note">Traccia orientativa basata sulle tue scelte. Compatibilità e prestazioni richiedono una verifica tecnica. Non è un preventivo.</p><div class="result-actions"><button class="button dark" id="download-project">Scarica la tua traccia ↓</button><a class="button outline" id="email-project">Prepara un’email ↗</a></div><p class="micro">L’email si aprirà nel tuo programma di posta: potrai rivederla prima di inviarla.</p><button class="underlink" id="restart-config">Ricomincia</button>`;
$('#email-project').href=`mailto:info@otconline.it?subject=${encodeURIComponent('Richiesta informazioni — '+p.title)}&body=${encodeURIComponent('Buongiorno, vorrei approfondire questa soluzione.\n\n'+resultText+'\n\nIl mio ente e i miei recapiti:\n')}`;
$('#download-project').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([resultText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='OTC-il-tuo-progetto.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});$('#restart-config').addEventListener('click',()=>{step=0;$('#config-form').hidden=false;$('#project-result').hidden=true;renderWizard();});}
function showClientTab(name){$$('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===name));b.tabIndex=b.dataset.tab===name?0:-1;});const p=$('#client-panel');p.setAttribute('aria-labelledby','tab-'+name);if(name==='impianto'){p.innerHTML=`<div class="client-row"><div><strong>Centrale Menestrello</strong><small>Sede comunale · ultima comunicazione simulata: adesso</small></div><span class="status-pill">Online</span></div><div class="client-row"><div><strong>Postazione Centro</strong><small>Uscita audio · dato dimostrativo</small></div><span class="status-pill">Online</span></div><div class="client-row"><div><strong>Postazione Borgata</strong><small>Connessione da verificare · esempio di segnalazione</small></div><span class="status-pill client-offline">Da verificare</span></div><p class="client-panel-note">Nella versione integrata, queste informazioni proverrebbero dagli impianti compatibili. I valori qui sono simulati.</p>`;}else if(name==='eventi'){p.innerHTML=`<div class="client-row"><div><strong>Festa della comunità</strong><small>Centro e Parco · programmazione di esempio</small></div><strong>18:00</strong></div><div class="client-row"><div><strong>Segnale orario</strong><small>Diffusore locale · ricorrenza di esempio</small></div><strong>12:00</strong></div><p class="client-panel-note">Menestrello 2026 prevede eventi ricorrenti e contenuti memorizzati sulla scheda. Questa vista non crea né modifica programmazioni reali.</p>`;}else{p.innerHTML=`<label for="support-text" class="support-label">Descrivi l’esigenza relativa all’impianto</label><textarea id="support-text" rows="3" placeholder="Per esempio: vorrei modificare gli orari degli annunci…"></textarea><a class="button dark" id="support-email" href="mailto:info@otconline.it">Prepara richiesta di assistenza ↗</a><p class="client-panel-note">Si apre una bozza nel tuo programma di posta. Nessun ticket viene inviato automaticamente; aggiungi l’identificativo del tuo impianto reale.</p>`;$('#support-text').addEventListener('input',()=>$('#support-email').href=`mailto:info@otconline.it?subject=${encodeURIComponent('Richiesta assistenza OTC')}&body=${encodeURIComponent($('#support-text').value+'\n\nEnte e identificativo impianto:\nRecapito:\n')}`);}}
$$('[data-client]').forEach(b=>b.addEventListener('click',()=>{showClientTab('impianto');openDialog($('#client-dialog'));}));$$('[data-tab]').forEach((b,i,all)=>{b.addEventListener('click',()=>showClientTab(b.dataset.tab));b.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%all.length;else if(e.key==='ArrowLeft')j=(i+all.length-1)%all.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=all.length-1;else return;e.preventDefault();showClientTab(all[j].dataset.tab);all[j].focus();});});

